INSERT INTO field_of_study_info (id, name, short_cut, degree_type, form_type, study_period, description, candidate_profile, graduate_profile, e_application_form_url, study_plan_url, further_study_possibility, exam_waiver_option, admission_procedure, estimated_number_of_admissions, accreditation_until) VALUES ('720d0a23-ed33-4291-88a6-eaacfc3b0a25', 'Aplikovaná informatika - Softwarové inženýrství', 'ai3-p', 'BACHELOR', 'PRESENT', 3, e'Studijní program se zaměřuje na dobré základní znalosti matematiky, algoritmizace a objektového modelování, na které navazují předměty s přímou aplikací (zejména programování, návrhy aplikací a správa informačních systémů a počítačových sítí, webové technologie, bezpečnost počítačových sítí).

Cílem je připravit absolventy k výkonu povolání, ve kterém je absolvent schopen na základě rámcového zadání řešit problémy v oblasti informačních technologií, jde zejména o oblasti návrhu, vývoje a implementace softwarových systémů s využitím základů matematiky a algoritmizace a správy počítačových systémů.

Studijní plán je sestaven tak, aby absolvent získal rovněž přehled a orientaci v problematice vývoje softwaru a návrhu a zabezpečení softwarových systémů a počítačových sítí v takové míře, aby byl schopný samostatně získávat a propojovat další odborné znalosti, dovednosti a způsobilosti nejen na základě praktické zkušenosti a jejího vyhodnocení, ale také samostatným studiem teoretických poznatků v oblasti oboru a celoživotním vzděláváním.

Program je koncipován tak, aby absolvent byl zároveň připraven v případě zájmu pokračovat ve studiu ve stejném, či příbuzném navazujícím magisterském studijním programu a měl pro něj kvalitní vstupní znalosti a dovednosti.', e'Středoškolské vzdělání zakončené maturitní zkouškou.

Potvrzení od lékaře nevyžadujeme, ale předpokládáme odpovídající zdravotní stav. Maturitní vysvědčení či životopis ve fázi podávání přihlášky nevyžadujeme.', e'Absolvent bakalářského studijního programu dovede (odborné dovednosti):

rozložit problém na podproblémy a identifikovat algoritmická primitiva pro řešení známých problémů;
srozumitelně a přesvědčivě sděluje odborníkům i laikům informace o povaze odborných problémů a vlastním názoru na jejich řešení;
vytvořit model systémové dynamiky;
aplikovat základní pravidla moderního webdesignu;
vytvořit návrhový model tříd reprezentující vybranou situaci;
analyzovat a navrhnout základní firemní procesy, identifikovat nefunkčnost návrhu struktury SW a popsat SW dle předloženého návrhu;
konfigurovat a spravovat operační systém;
navrhnout konceptuální model jednoduché aplikace, implementovat model v relačním databázovém systému;
navrhnout a v programovacím jazyce zapsat vlastní objektové datové struktury;
navrhnout použití vhodných matematických principů při implementaci;
vytvořit, nakonfigurovat a otestovat model sítě;
vypočítat základní charakteristiky ve statistickém souboru;
spravovat základní funkce operačního systému;
porozumět odbornému textu a schopnost psát odborné texty v cizím jazyce
prakticky implementovat vybrané algoritmy počítačové grafiky (transformace, projektce, viditelnosti);
formálně reprezentovat pojmy a vztahy mezi nimi v ucelené podobě (modelu) pro danou problémovou oblast za účelem vyjádření sémantiky;
vybrat a aplikovat moderní metodiku při návrhu, vývoji a implementaci softwarového systému;
vytvořit webovou aplikaci s využitím moderních technologií;
analyzovat a řešit problematiku z oblasti zpracování obrazových dat;
aplikovat základní postupy ontologického modelování, postupovat při reprezentaci sémantiky projektovým způsobem;
vyvíjet softwarový systém s využitím vhodné metodiky pro vývoj;
navrhnout a vytvořit pokročilý databázový systém;
k návrhu a implementaci single page aplikace.', 'https://stag.uhk.cz/portal/studium/uchazec/eprihlaska.html', 'https://stag.uhk.cz/StagPortletsJSR168/CleanUrl?urlid=prohlizeni-browser-vizualizace&browserFakulta=FIM&browserRok=2022&browserProgram=1848&browserObor=4094&browserPlan=54790', 'https://www.uhk.cz/cs/fakulta-informatiky-a-managementu/prijimaci-zkousky/studijni-programy/aplikovana-informatika-34', e'Děkan FIM UHK může prominout přijímací zkoušku z matematiky v bakalářských studijních programech Aplikovaná informatika a Informační management, jestliže uchazeč o prominutí přijímací zkoušky požádá, na FIM UHK dosud nestudoval, ukončil nebo ukončí středoškolské studium maturitní zkouškou ve školním roce 2015/16 až 2022/23 a splní alespoň jednu z následujících podmínek:
úspěšně složil maturitní zkoušku z matematiky, kterou organizuje CERMAT, s percentilem alespoň 80;
úspěšně složil zkoušku Matematika rozšiřující nebo Matematika+ s percentilem alespoň 50, kterou organizuje CERMAT;
v uplynulých 5 letech a nejpozději do 30.4 2023 složil Národní srovnávací zkoušku z matematiky, kterou organizuje SCIO, s percentilem alespoň 80;
v některé z níže uvedených soutěží evidovaných MŠMT se v průběhu svého středoškolského studia
zúčastnil krajského kola Matematické olympiády kategorie A, B, C nebo P;
zúčastnil krajského kola Fyzikální olympiády kategorie A, B, C, D;
zúčastnil krajského kola Středoškolské odborné činnosti v oborech 01 Matematika a statistika nebo v oboru 18 Informatika;
zúčastnil ústředního kola Celostátní matematické soutěže žáků SOŠ a SOU v kategorii VI. nebo VII;
zúčastnil krajského kola Soutěže v programování v kategorii pro střední školy;
zúčastnil ústředního kola soutěže České hlavičky;
zúčastnil ústředního kola Soutěže vědeckých a technických projektů EXPO SCIENCE AMAVET;
umístil do 10. místa v Logické olympiádě v krajském kole v kategorii C.
úspěšně složil závěrečnou zkoušku z matematiky v kurzu na Ústavu jazykové odborné přípravy (dále jen ÚJOP UK) na 80 % a více (výsledek bude na základě žádosti a souhlasu uchazeče ověřen přímo na ÚJOP UK; ověřené doklady není třeba přikládat).
úspěšné absolvování mezinárodně platné zkoušky Advanced Placement s výsledkem 5 nebo 4 alespoň v jednom z následujících předmětů AP Calculus AB, AP Calculus BC, AP Statistics, AP Computer Science A, AP Computer Science Principles.', null, 120, '2031-11-01 22:56:58.000000');
INSERT INTO field_of_study_info (id, name, short_cut, degree_type, form_type, study_period, description, candidate_profile, graduate_profile, e_application_form_url, study_plan_url, further_study_possibility, exam_waiver_option, admission_procedure, estimated_number_of_admissions, accreditation_until) VALUES ('981f5d2d-6a0e-491f-b54f-c93d0c75aef9', 'Aplikovaná informatika', 'ai2-p', 'MASTER', 'PRESENT', 2, '-', 'O studium v navazujícím magisterském studijním programu Aplikovaná informatika se uchází student, který má ukončené bakalářské (magisterské) studium v tomto nebo příbuzném programu a ve svém předchozím vysokoškolském studiu úspěšně absolvoval výuku matematiky v rozsahu minimálně 2 semestrů po 4 hodinách týdně nebo v obdobném rozsahu, tj. cca 120 hodin výuky rozložené do jiného počtu semestrů.', e'Student bude veden k práci v týmu, případně k řízení týmu.
Studium se koncentruje na rozšíření teoretických znalostí a principů souvisejících se zpracováním informací, výpočetní složitostí, efektivitou implementace, návrhem a řízením datových struktur, moderními komunikačními prostředky a příbuznou problematikou, včetně porozumění technickým problémům.
Absolvent bude vybaven teoretickými znalostmi v předmětech, které podporují logické a analytické myšlení. Získá přehled a porozumí principům, na kterých jsou budovány moderní informační technologie a systémy. Současně by měl ovládat jeden světový jazyk na velmi dobré úrovni (podporován bude anglický jazyk).
Kromě povinné výuky specializovaných odborných předmětů se bude formou volitelné výuky vzdělávat v předmětech ekonomických, společenskovědních a bude se účastnit seminářů z anglického jazyka a pohybových aktivit.', 'https://stag.uhk.cz/portal/studium/uchazec/eprihlaska.html', 'https://stag.uhk.cz/StagPortletsJSR168/CleanUrl?urlid=prohlizeni-browser-vizualizace&browserFakulta=FIM&browserRok=2021&browserProgram=1453&browserObor=3462&browserPlan=54339', 'https://www.uhk.cz/cs/fakulta-informatiky-a-managementu/prijimaci-zkousky/studijni-programy/aplikovana-informatika-35', 'Z uchazečů, kteří splňují výše uvedené požadavky, bude sestaveno pořadí nejlepších podle dosaženého studijního průměru za celé studium (bez započtení známek ze státní závěrečné zkoušky, vypočteného v souladu s čl. 15 Studijního a zkušebního řádu UHK). Na základě tohoto pořadí bude přijata ke studiu polovina předpokládaného počtu studentů pro daný akademický rok. Druhá polovina předpokládaného počtu míst bude obsazena na základě pořadí nejlepších sestaveného dle bodového ohodnocení výsledků písemné přijímací zkoušky z informatiky a matematiky (max. počet bodů 100 bodů). Pokud se student umístí v obou uvedených pořadích, bude přijat z pořadí, v němž dosáhl lepšího umístění.', null, 30, '2024-12-31 22:20:12.000000');
INSERT INTO field_of_study_info (id, name, short_cut, degree_type, form_type, study_period, description, candidate_profile, graduate_profile, e_application_form_url, study_plan_url, further_study_possibility, exam_waiver_option, admission_procedure, estimated_number_of_admissions, accreditation_until) VALUES ('c6925ccb-005d-46b8-842e-0a181ef4c2df', 'Ekonomika a management', 'em2-p', 'MASTER', 'PRESENT', 2, '-', 'O studium v navazujícím magisterském studijním programu Aplikovaná informatika se uchází student, který má ukončené bakalářské (magisterské) studium v tomto nebo příbuzném programu a ve svém předchozím vysokoškolském studiu úspěšně absolvoval výuku matematiky v rozsahu minimálně 2 semestrů po 4 hodinách týdně nebo v obdobném rozsahu, tj. cca 120 hodin výuky rozložené do jiného počtu semestrů.', e'Student bude veden k práci v týmu, případně k řízení týmu.
Studium se koncentruje na rozšíření teoretických znalostí a principů souvisejících se zpracováním informací, výpočetní složitostí, efektivitou implementace, návrhem a řízením datových struktur, moderními komunikačními prostředky a příbuznou problematikou, včetně porozumění technickým problémům.
Absolvent bude vybaven teoretickými znalostmi v předmětech, které podporují logické a analytické myšlení. Získá přehled a porozumí principům, na kterých jsou budovány moderní informační technologie a systémy. Současně by měl ovládat jeden světový jazyk na velmi dobré úrovni (podporován bude anglický jazyk).
Kromě povinné výuky specializovaných odborných předmětů se bude formou volitelné výuky vzdělávat v předmětech ekonomických, společenskovědních a bude se účastnit seminářů z anglického jazyka a pohybových aktivit.', 'https://stag.uhk.cz/portal/studium/uchazec/eprihlaska.html', 'https://stag.uhk.cz/StagPortletsJSR168/CleanUrl?urlid=prohlizeni-browser-vizualizace&browserFakulta=FIM&browserRok=2021&browserProgram=1453&browserObor=3462&browserPlan=54339', 'https://www.uhk.cz/cs/fakulta-informatiky-a-managementu/prijimaci-zkousky/studijni-programy/aplikovana-informatika-35', 'Z uchazečů, kteří splňují výše uvedené požadavky, bude sestaveno pořadí nejlepších podle dosaženého studijního průměru za celé studium (bez započtení známek ze státní závěrečné zkoušky, vypočteného v souladu s čl. 15 Studijního a zkušebního řádu UHK). Na základě tohoto pořadí bude přijata ke studiu polovina předpokládaného počtu studentů pro daný akademický rok. Druhá polovina předpokládaného počtu míst bude obsazena na základě pořadí nejlepších sestaveného dle bodového ohodnocení výsledků písemné přijímací zkoušky z informatiky a matematiky (max. počet bodů 100 bodů). Pokud se student umístí v obou uvedených pořadích, bude přijat z pořadí, v němž dosáhl lepšího umístění.', null, 30, '2024-12-31 22:20:12.000000');
INSERT INTO field_of_study_info (id, name, short_cut, degree_type, form_type, study_period, description, candidate_profile, graduate_profile, e_application_form_url, study_plan_url, further_study_possibility, exam_waiver_option, admission_procedure, estimated_number_of_admissions, accreditation_until) VALUES ('de7f9f7c-1467-442c-b4a2-13479b6b33c1', 'Datová věda', 'dv2-p', 'MASTER', 'PRESENT', 2, '-', 'O studium v navazujícím magisterském studijním programu Aplikovaná informatika se uchází student, který má ukončené bakalářské (magisterské) studium v tomto nebo příbuzném programu a ve svém předchozím vysokoškolském studiu úspěšně absolvoval výuku matematiky v rozsahu minimálně 2 semestrů po 4 hodinách týdně nebo v obdobném rozsahu, tj. cca 120 hodin výuky rozložené do jiného počtu semestrů.', e'Student bude veden k práci v týmu, případně k řízení týmu.
Studium se koncentruje na rozšíření teoretických znalostí a principů souvisejících se zpracováním informací, výpočetní složitostí, efektivitou implementace, návrhem a řízením datových struktur, moderními komunikačními prostředky a příbuznou problematikou, včetně porozumění technickým problémům.
Absolvent bude vybaven teoretickými znalostmi v předmětech, které podporují logické a analytické myšlení. Získá přehled a porozumí principům, na kterých jsou budovány moderní informační technologie a systémy. Současně by měl ovládat jeden světový jazyk na velmi dobré úrovni (podporován bude anglický jazyk).
Kromě povinné výuky specializovaných odborných předmětů se bude formou volitelné výuky vzdělávat v předmětech ekonomických, společenskovědních a bude se účastnit seminářů z anglického jazyka a pohybových aktivit.', 'https://stag.uhk.cz/portal/studium/uchazec/eprihlaska.html', 'https://stag.uhk.cz/StagPortletsJSR168/CleanUrl?urlid=prohlizeni-browser-vizualizace&browserFakulta=FIM&browserRok=2021&browserProgram=1453&browserObor=3462&browserPlan=54339', 'https://www.uhk.cz/cs/fakulta-informatiky-a-managementu/prijimaci-zkousky/studijni-programy/aplikovana-informatika-35', 'Z uchazečů, kteří splňují výše uvedené požadavky, bude sestaveno pořadí nejlepších podle dosaženého studijního průměru za celé studium (bez započtení známek ze státní závěrečné zkoušky, vypočteného v souladu s čl. 15 Studijního a zkušebního řádu UHK). Na základě tohoto pořadí bude přijata ke studiu polovina předpokládaného počtu studentů pro daný akademický rok. Druhá polovina předpokládaného počtu míst bude obsazena na základě pořadí nejlepších sestaveného dle bodového ohodnocení výsledků písemné přijímací zkoušky z informatiky a matematiky (max. počet bodů 100 bodů). Pokud se student umístí v obou uvedených pořadích, bude přijat z pořadí, v němž dosáhl lepšího umístění.', null, 30, '2024-12-31 22:20:12.000000');
INSERT INTO field_of_study_info (id, name, short_cut, degree_type, form_type, study_period, description, candidate_profile, graduate_profile, e_application_form_url, study_plan_url, further_study_possibility, exam_waiver_option, admission_procedure, estimated_number_of_admissions, accreditation_until) VALUES ('09451426-6999-47d1-a0fd-31384b67e124', 'Informační management', 'im2-p', 'MASTER', 'PRESENT', 2, '-', 'O studium v navazujícím magisterském studijním programu Aplikovaná informatika se uchází student, který má ukončené bakalářské (magisterské) studium v tomto nebo příbuzném programu a ve svém předchozím vysokoškolském studiu úspěšně absolvoval výuku matematiky v rozsahu minimálně 2 semestrů po 4 hodinách týdně nebo v obdobném rozsahu, tj. cca 120 hodin výuky rozložené do jiného počtu semestrů.', e'Student bude veden k práci v týmu, případně k řízení týmu.
Studium se koncentruje na rozšíření teoretických znalostí a principů souvisejících se zpracováním informací, výpočetní složitostí, efektivitou implementace, návrhem a řízením datových struktur, moderními komunikačními prostředky a příbuznou problematikou, včetně porozumění technickým problémům.
Absolvent bude vybaven teoretickými znalostmi v předmětech, které podporují logické a analytické myšlení. Získá přehled a porozumí principům, na kterých jsou budovány moderní informační technologie a systémy. Současně by měl ovládat jeden světový jazyk na velmi dobré úrovni (podporován bude anglický jazyk).
Kromě povinné výuky specializovaných odborných předmětů se bude formou volitelné výuky vzdělávat v předmětech ekonomických, společenskovědních a bude se účastnit seminářů z anglického jazyka a pohybových aktivit.', 'https://stag.uhk.cz/portal/studium/uchazec/eprihlaska.html', 'https://stag.uhk.cz/StagPortletsJSR168/CleanUrl?urlid=prohlizeni-browser-vizualizace&browserFakulta=FIM&browserRok=2021&browserProgram=1453&browserObor=3462&browserPlan=54339', 'https://www.uhk.cz/cs/fakulta-informatiky-a-managementu/prijimaci-zkousky/studijni-programy/aplikovana-informatika-35', 'Z uchazečů, kteří splňují výše uvedené požadavky, bude sestaveno pořadí nejlepších podle dosaženého studijního průměru za celé studium (bez započtení známek ze státní závěrečné zkoušky, vypočteného v souladu s čl. 15 Studijního a zkušebního řádu UHK). Na základě tohoto pořadí bude přijata ke studiu polovina předpokládaného počtu studentů pro daný akademický rok. Druhá polovina předpokládaného počtu míst bude obsazena na základě pořadí nejlepších sestaveného dle bodového ohodnocení výsledků písemné přijímací zkoušky z informatiky a matematiky (max. počet bodů 100 bodů). Pokud se student umístí v obou uvedených pořadích, bude přijat z pořadí, v němž dosáhl lepšího umístění.', null, 30, '2024-12-31 22:20:12.000000');


INSERT INTO university_event (id, name, type, from_time, to_time, location, repetition_time_in_minutes, description) VALUES ('0a866a34-3728-4228-930c-94a56b49fa1c', e'Přijímačky z matematiky nanečisto	', 'WORKSHOP', '2023-02-04 09:00:01.000000', '2023-02-04 13:00:01.000000', 'J4', null, 'Vyzkoušejte si přijímací zkoušky na svůj obor');
INSERT INTO university_event (id, name, type, from_time, to_time, location, repetition_time_in_minutes, description) VALUES ('107aa732-f335-4e3c-9a54-310d3d2f20d3', 'Infinite Run nebo fantasy RPG? ', 'WORKSHOP', '2023-02-04 09:00:01.000000', '2023-02-04 13:00:01.000000', 'J11', null, 'Vyzkoušej nějakou z našich her');
INSERT INTO university_event (id, name, type, from_time, to_time, location, repetition_time_in_minutes, description) VALUES ('c43efbd8-adab-41da-b066-51b3eb32fc89', 'Kavárna u věčného studenta', 'SIDE_EVENT', '2023-02-04 09:00:01.000000', '2023-02-04 13:00:01.000000', 'relax zóna', null, 'občerstvení a povídání se studenty jednotlivých programů');
INSERT INTO university_event (id, name, type, from_time, to_time, location, repetition_time_in_minutes, description) VALUES ('4fafb2b9-265f-469a-b4f0-b8b42bdae2c9', 'Management cestovního ruchu', 'PRESENTATION', '2023-02-04 09:00:01.000000', '2023-02-04 13:00:01.000000', 'J3', null, 'přednáška o konkrétních studijních programech');
INSERT INTO university_event (id, name, type, from_time, to_time, location, repetition_time_in_minutes, description) VALUES ('db275f01-cf67-43db-9877-a498f02980cd', 'Ekonomika a management', 'PRESENTATION', '2023-02-04 09:00:01.000000', '2023-02-04 13:00:01.000000', 'J13', null, 'přednáška o konkrétních studijních programech');
INSERT INTO university_event (id, name, type, from_time, to_time, location, repetition_time_in_minutes, description) VALUES ('a9f2004f-e3b8-46a1-8969-48b5eb0bf0ed', 'Robot + Chatbot = FIMbot', 'WORKSHOP', '2023-02-04 09:00:01.000000', '2023-02-04 13:00:01.000000', 'naproti J4', null, 'Vyzkoušej si, jak se programuje a ovládá humanoidní robot, posuď, jestli má nejnovější chatbot od OpenAI smysl pro humor, nebo pomocí IoT senzorů zjisti, jak je na FIMce čistý vzduch.');
INSERT INTO university_event (id, name, type, from_time, to_time, location, repetition_time_in_minutes, description) VALUES ('9e8c867c-78c9-4efe-b779-b2921e7aad16', 'Aplikovaná informatika', 'PRESENTATION', '2023-02-04 09:00:01.000000', '2023-02-04 13:00:01.000000', 'J12', null, 'přednáška o konkrétních studijních programech');
INSERT INTO university_event (id, name, type, from_time, to_time, location, repetition_time_in_minutes, description) VALUES ('600f7f37-fee5-4359-a1dc-28700eec01cf', 'Úvodní přednáška pro všechny studijní programy', 'PRESENTATION', '2023-02-04 09:00:01.000000', '2023-02-04 12:00:01.000000', 'J1', 60, 'Obecné informace o studiu');

INSERT INTO video_info (id, name, url, thumbnail, description) VALUES ('76406ee9-149b-4843-b978-3c996d9da40c', 'APLIKOVANÁ INFORMATIKA, INFORMAČNÍ MANAGEMENT, DATOVÁ VĚDA', 'https://www.youtube.com/watch?v=xG3TBecnXE8', 'https://i3.ytimg.com/vi/xG3TBecnXE8/maxresdefault.jpg', 'Přemýšlíš o studiu na Fakultě informatiky a managementu Univerzity Hradec Králové? Podívej se na prezentaci programů Aplikovaná informatika, Informační management a Datová věda, třeba Tě právě jeden z nich osloví.');
INSERT INTO video_info (id, name, url, thumbnail, description) VALUES ('97ed568c-4f18-46e1-8341-39ea6cc82d3d', 'MANAGEMENT CESTOVNÍHO RUCHU', 'https://www.youtube.com/watch?v=EvcxVPnve-I', 'https://i3.ytimg.com/vi/EvcxVPnve-I/maxresdefault.jpg', 'Přemýšlíš o studiu na Fakultě informatiky a managementu Univerzity Hradec Králové? Podívej se na prezentaci programu Management cestovního ruchu');
INSERT INTO video_info (id, name, url, thumbnail, description) VALUES ('0965930d-dcdd-48e9-a6b8-e8d0e4e4fbaf', 'FAKULTA INFORMATIKY A MANAGEMENTU', 'https://www.youtube.com/watch?v=nH0dblvQThY', 'https://i3.ytimg.com/vi/nH0dblvQThY/maxresdefault.jpg', '{=} FIMka nabízí studium v oblasti informatiky');
INSERT INTO video_info (id, name, url, thumbnail, description) VALUES ('b3bde153-52d2-4178-a021-563c60cf1b67', 'Záznam ze Dnů otevřených dveří 2021', 'https://www.youtube.com/watch?v=iIoIkk9DHTo&t=4898s', null, 'Podívej se jak to vzpadalo na předchozím dnu otevřených dveří!');
INSERT INTO video_info (id, name, url, thumbnail, description) VALUES ('774e31b7-68f5-466b-8ab3-92b2708d16c6', 'EKONOMIKA A MANAGEMENT', 'https://www.youtube.com/watch?v=MpCAH57sAGM', 'http://i3.ytimg.com/vi/MpCAH57sAGM/hqdefault.jpg', 'Přemýšlíš o studiu na Fakultě informatiky a managementu Univerzity Hradec Králové? Podívej se na prezentaci programu Ekonomika a management');
